# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-latest
            os-version: ubuntu-latest
            sudo-cmd: sudo
          - name: macos-latest
            os-version: macos-latest
            sudo-cmd: sudo
          - name: windows-latest
            os-version: windows-latest
            sudo-cmd: ''
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Set up Node js
      - name: Use Node.js
        uses: actions/setup-node@v2
      
      # Install necessary packages on the machine
      - name: install ubuntu requirements
        if: matrix.os-version == 'ubuntu-latest'
        run: sudo apt-get install -y dpkg fakeroot
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install the packages and SASS
      - run: npm ci
      - run: ${{ matrix.sudo-cmd }} npm install -g sass
      - run: mkdir -p css
      
      - name: install macos requirements
        if: matrix.os-version == 'macos-latest'
        run: npm install -D macos-alias
      
      # Build the app
      - run: npm run build
      - run: npm run sass
      - run: npm run make
      
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: out/make/**/*.*
  
  release:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download all Build Artifacts
        uses: actions/download-artifact@v2
        with:
          path: build
  
      - name: GitHub Tag
        id: tag_release
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/*
          fail_on_unmatched_files: true
          tag_name: ${{ steps.tag_release.outputs.new_tag }}
  
