# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    strategy:
      matrix:
        os-version: [ubuntu-latest]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install necessary packages on the machine
      - name: prepare machine
        run: sudo apt-get install -y dpkg fakeroot
      
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install the packages and SASS
      - run: npm ci
      - run: npm install -g sass
      - run: mkdir -p css
      
      # Build the app
      - run: npm run build
      - run: npm run sass
      - run: npm run make
  
      - name: GitHub Tag
        id: tag_release
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
      - uses: actions/checkout@v2
        with:
          ref:  ${{ steps.tag_release.outputs.new_tag }}
          clean: false
  
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: out/make/**/*.*
          fail_on_unmatched_files: true
          tag_name: ${{ steps.tag_release.outputs.new_tag }}
  
